name: GitHub Action for pylint test code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
    - 'python/tests/**.py'
  workflow_dispatch:

jobs:
  build:
    name: GitHub Action for pylint test code
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for pylint test code
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: "pip install -r ./python/requirements.txt ; make -C python/ lint-tests"
