name: GitHub Action for integration tests

on:
  push:
    branches: [ main ]
    paths:
    - '**.py'
  workflow_dispatch:

jobs:
  build:
    name: GitHub Action for integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: GitHub Action for pytest
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: "pip install -r ./python/requirements.txt ; make test-integration"
